export const STRING = {
    SAYLANI: "Saylani",
    SAHULAT: "Sahulat",
    LOGIN: "Login",
    REGISTER: "Register",
    REGISTER_NOW: "Register Now",
    SHAPPING_FINANCIAL: "Shaping Financial",
    FUTURES: "Futures",
    WITH_CARE: "with Care",
    HERO_PERA: "Interest-free loans to empower your dreams. Join thousands of families building a better tomorrow with Saylani Sahulat.",
    GET_STARTED_BUTTON: "Get Started",
    INTERESTE_RATE: "Interest Rate",
    MAX_LOAN: "Max Loan",
    LOAN_SCHEMES: "Our Loan Schemes",
    TAILORED: "Tailored",
    FINANCIAL_SOL: "Financial Solutions",
    FOR_EVERY: "for Every Need",
    CATEGORY_PERA: "Saylani Welfare provides interest-free loans across various categories to help you achieve your goals without any financial burden.",
    APPLY_NOW: "Apply Now",
    LOAN_CALCULATOR: "Loan Calculator",
    CALCULATOR_PLAN: "Plan your financial journey with zero interest",
    CUSTOMIZE_LOAN: "Customize Your Loan",
    SELECT_CATEGORIES: "Select Category",
    WEDDING_LOANS: "Wedding Loans",
    HOME_LOANS: "Home Construction",
    BUSINESS_LOANS: "Business Startup",
    EDUCATIONS_LOANS: "Education Loans",
    LOAN_AMOUNT: "Loan Amount",
    PKR: 'PKR',
    DEPOSIT: "Deposit",
    YEARS: "Years",
    ESTIMATED_RES: "Estimated Result",
    MONTHLY_INST: "Monthly Installment",
    LOAN_TYPE: "Loan Type:",
    TOTAL_DURATION: "Total Duration",
    UPFRONT_DEPOSIT: "Upfront Deposit",
    PROCEED_BTN: "Proceed",
    INSTRUCTION: '*Calculations are based on 0% interest rate policy.',
    TRUST_YEAR: "Years of Trust",
    ABOUT_SAYLANI: "About Saylani Sahulat",
    WE_PROVIDE: "We provide more than",
    JUST_LOAN: 'just a loan.',
    ABOUT_PARA: "Saylani Welfare International Trust has been working for decades to eradicate poverty. With Saylani Sahulat, we are digitizing the spirit of Qarz-e-Hasana, making it easier for every Pakistani to build their future with dignity.",
    FOOTER_RESERVED: "© 2026 Qarz-e-Hasana Program. All rights reserved.",
    DEVELOPED_BY: "Developed by",
    NAVEED_AHMED: "NAVEED AHMED",
    CREATE_ACCOUNT: "Create Account",
    REG_SUBTITLE: "Enter details to get your temporary password",
    CNIC_NUM: "CNIC Number",
    FULL_NAME: "Full Name",
    EMAIL_ADD: "Email Address",
    PROCESSING_LOAD: "Processing...",
    ALREADY_HAVE_AN: "Already have an account?",
    LOGIN_HERE: "Login here",
    WELCOME_BACK: "Welcome Back",
    LOGIN_SUBTITILE: "Log in with your registered email and password",
    LOGIN_BTN: "Securing Session...",
    SIGN_IN: "Sign In",
    NOT_REG_YET: "Not registered yet?",
    CREATE_AN_AC: " Create an account",
    SET_NEW_PASS: "Set New Password",
    NEW_PASS_SUBTITLE: "Your security is our priority. Please update your temporary password to continue.",
    TEMP_PASS: "Temporary Password",
    NEW_SEC_PASS: "New Secure Password",
    CONF_NEW_PASS: "Confirm New Password",
    UPDATING: "Updating...",
    SEC_MY_AC: "Secure My Account",
    APPLICATION: "Application",
    SUBMISSION: "Submission",
    TRACK_YOUR: "Track Your",
    REQUEST: "Request",
    VERIFIED_USER: "Verified User",
    KHUSH_AMDEED: "Khush Amdeed",
    APP_STARTED_MSG: "Apni Application Shuru Karein.",
    AAP_KI_APP: "Aapki Application",
    REVIEW: "Review",
    REVIEW_MSG: "Ho Rahi Hai.",
    MUBARAK_HU_APP: "Mubarak Ho! Application",
    APPROVE: "Approve",
    HO_GAYE: "Ho Gayi.",
    UPDATE: "Update:",
    UPDATE_MSG: "Agay Nahi Barh Saki.",
    NEW_MSG: "Bas chand steps mazeed aur aapka interest-free loan process shuru ho jayega.",
    PENDING_MSG: "Humari team aapke documents ki tasdeeq kar rahi hai. Jald hi faisla suna diya jayega.",
    APPROVED_MSG: "Aapka loan manzoor ho chuka hai. Niche di gayi digital slip download kar ke process mukammal karein.",
    REJECTED_MSG: "Humein afsos hai ke aapki application is martaba approve nahi ho saki. Details niche mulahiza karein.",
    APP_STATUS: "Application Status",
    PROGRESS: "Progress",
    LOAN_REQ: "Loan Requirements",
    CATEGORY: "Category",
    CHOOSE_CATEGORY: "Choose Category",
    SUB_CAT: "Sub Category",
    CHOOSE_SUBCAT: "Choose Sub-option",
    LOAN_PERIOD: "Loan Period",
    SELECT_TEN: "Select Tenure",
    CONTACT_INFO: "Contact Info",
    PHONE_NUM: "Phone Number",
    ADDRESS: "Residential Address",
    ZAMANAT_DAAR: "Zamanat Daar (Guarantors)",
    GUARANTOR: "Guarantor",
    DATA: "Data",
    FINAL_VER_SLIP: "Final Verification Slip",
    LOAN_PLAN: "Loan Plan",
    TOTAL_AMOUNT: "Total Amount",
    APPLICANT: "Applicant",
    GUARANTORS: "Guarantors",
    VER_SUCC_MSG: "Verification successful. Ready for submission.",
    APP_REVIEW: "Application Review",
    DEAR: "Dear",
    HAMARI: "Hamari",
    REVIEW_COMM: "Review Committee",
    REJ_MSG: " ne aapki request ka jaiza liya hai. Mazzrat ke sath, is martaba aapki application eligibility criteria par poori nahi utar saki. Aap naye jazbe ke sath dobara apply kar sakte hain.",
    REC_ACTION: "Recommended Actions",
    START_NEW_BTN: "Start New Application",
    SWIT: "Saylani Welfare International Trust",
    SWT: "Saylani Welfare Trust",
    LOAN_ASS_SLIP: "Loan Assistance Slip",
    TOKEN_NUM: "Token Number",
    DATE: "Date",
    TIME: "Time",
    LOCATION: "Location",
    DOWNLOAD_NOTE: "Note: Please bring your original CNIC and this slip for verification.",
    DIGITAL_SLIP: "Download Digital Slip",
    BACK_BTN: "Back",
    VERIFICATION: "Verification",
    DETAILS: "Details",
    FINANCIAL_STANDING: "Financial Standing",
    OCCUPATION: "Occupation",
    SEL_OCC: "Select Occupation",
    SALARIED: "Salaried",
    BUSINESS: "Business",
    SELF_EMP: "Self-Employed",
    MONTHLY_INCOME: "Monthly Income",
    MONTHLY_EXPENCE: "Monthly Expenses",
    DURATION: "Duration",
    SOURCE: "Source",
    
}